[build]
  command = "cd frontend && npm run build"
  publish = "frontend/dist"
  functions = "api"

[build.environment]
  PYTHON_VERSION = "3.9"
  
[functions]
  included_files = ["marketing_genius_tool.py"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 